# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f27f76571479be7f7760f4e9d9c6770b080d034f5e4b24722df2465da8b2305ae04d1035308acb736191a94aaee9402cc4e305c01f9bef80cabda2569df88d38

test:
  secret_key_base: 6fcb7e4e3491a7d8e2ffc7916c87a1f1bb0f3eb18f922e8bdd0535654ab4079d6af744bff22d0f212fd2ead3020844a7674afeb0036df85f26a077c6a3a8a1ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
